# tell docker what version of the docker-compose.yml we're using
version: '3'

#define the network
networks:
  node-network:

# start the services section
services:
  # define the name of our services
  # corresponds to the "--name" parameter
  nodejs:
    # define the directory where the build should happened
    # i.e. where the Dockerfile of the service is located
    # all paths are relative to the location of docker-compose.yml
    build:
      context: ./nodejs
    # reserve a tty - otherwise the container shuts down immediately
    # corresponds to the "-i" flag
    tty: true
    # expose container port 10001 to 8080 on host
    ports:
      - "8080:10001"
    # mount the src directory of the host to /home/node/src in the container
    # corresponds to the "-v" option
    volumes:
      - ..:/home/node/app
    # connect to the network
    # corresponds to the "--network" option
    networks:
      - node-network